/*******************************************************************************
 * Copyright (c) 2014 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the estimation part of the SO.
 * 
 * <p>Java class for EstimationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstimationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="PopulationEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PopulationEstimatesType" minOccurs="0"/>
 *         &lt;element name="PrecisionPopulationEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PrecisionPopulationEstimatesType" minOccurs="0"/>
 *         &lt;element name="IndividualEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}IndividualEstimatesType" minOccurs="0"/>
 *         &lt;element name="PrecisionIndividualEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PrecisionIndividualEstimatesType" minOccurs="0"/>
 *         &lt;element name="Residuals" type="{http://www.pharmml.org/2013/03/StandardisedOutput}ResidualsType" minOccurs="0"/>
 *         &lt;element name="Predictions" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PredictionsType" minOccurs="0"/>
 *         &lt;element name="Likelihood" type="{http://www.pharmml.org/2013/03/StandardisedOutput}LikelihoodType" minOccurs="0"/>
 *         &lt;element name="TargetToolMessages" type="{http://www.pharmml.org/2013/03/StandardisedOutput}TargetToolMessagesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstimationType", propOrder = {
    "populationEstimates",
    "precisionPopulationEstimates",
    "individualEstimates",
    "precisionIndividualEstimates",
    "residuals",
    "predictions",
    "likelihood",
    "targetToolMessages"
})
public class Estimation
    extends PharmMLRootType
{

    @XmlElement(name = "PopulationEstimates")
    protected PopulationEstimates populationEstimates;
    @XmlElement(name = "PrecisionPopulationEstimates")
    protected PrecisionPopulationEstimates precisionPopulationEstimates;
    @XmlElement(name = "IndividualEstimates")
    protected IndividualEstimates individualEstimates;
    @XmlElement(name = "PrecisionIndividualEstimates")
    protected PrecisionIndividualEstimates precisionIndividualEstimates;
    @XmlElement(name = "Residuals")
    protected Residuals residuals;
    @XmlElement(name = "Predictions")
    protected DataSetType predictions;
    @XmlElement(name = "Likelihood")
    protected Likelihood likelihood;
    @XmlElement(name = "TargetToolMessages")
    protected TargetToolMessages targetToolMessages;

    /**
     * Gets the value of the populationEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PopulationEstimates }
     *     
     */
    public PopulationEstimates getPopulationEstimates() {
        return populationEstimates;
    }

    /**
     * Sets the value of the populationEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopulationEstimates }
     *     
     */
    public void setPopulationEstimates(PopulationEstimates value) {
        this.populationEstimates = value;
    }

    /**
     * Gets the value of the precisionPopulationEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimates }
     *     
     */
    public PrecisionPopulationEstimates getPrecisionPopulationEstimates() {
        return precisionPopulationEstimates;
    }

    /**
     * Sets the value of the precisionPopulationEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimates }
     *     
     */
    public void setPrecisionPopulationEstimates(PrecisionPopulationEstimates value) {
        this.precisionPopulationEstimates = value;
    }

    /**
     * Gets the value of the individualEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimates }
     *     
     */
    public IndividualEstimates getIndividualEstimates() {
        return individualEstimates;
    }

    /**
     * Sets the value of the individualEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimates }
     *     
     */
    public void setIndividualEstimates(IndividualEstimates value) {
        this.individualEstimates = value;
    }

    /**
     * Gets the value of the precisionIndividualEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionIndividualEstimates }
     *     
     */
    public PrecisionIndividualEstimates getPrecisionIndividualEstimates() {
        return precisionIndividualEstimates;
    }

    /**
     * Sets the value of the precisionIndividualEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionIndividualEstimates }
     *     
     */
    public void setPrecisionIndividualEstimates(PrecisionIndividualEstimates value) {
        this.precisionIndividualEstimates = value;
    }

    /**
     * Gets the value of the residuals property.
     * 
     * @return
     *     possible object is
     *     {@link Residuals }
     *     
     */
    public Residuals getResiduals() {
        return residuals;
    }

    /**
     * Sets the value of the residuals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residuals }
     *     
     */
    public void setResiduals(Residuals value) {
        this.residuals = value;
    }

    /**
     * Gets the value of the predictions property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getPredictions() {
        return predictions;
    }

    /**
     * Sets the value of the predictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setPredictions(DataSetType value) {
        this.predictions = value;
    }

    /**
     * Gets the value of the likelihood property.
     * 
     * @return
     *     possible object is
     *     {@link Likelihood }
     *     
     */
    public Likelihood getLikelihood() {
        return likelihood;
    }

    /**
     * Sets the value of the likelihood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Likelihood }
     *     
     */
    public void setLikelihood(Likelihood value) {
        this.likelihood = value;
    }

    /**
     * Gets the value of the targetToolMessages property.
     * 
     * @return
     *     possible object is
     *     {@link TargetToolMessages }
     *     
     */
    public TargetToolMessages getTargetToolMessages() {
        return targetToolMessages;
    }

    /**
     * Sets the value of the targetToolMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetToolMessages }
     *     
     */
    public void setTargetToolMessages(TargetToolMessages value) {
        this.targetToolMessages = value;
    }
    
    /**
     * Creates a new empty {@link PopulationEstimates} populationEstimates element, adds it to the current object and returns it.
     * @return The created {@link PopulationEstimates} object.
     */
    public PopulationEstimates createPopulationEstimates(){
    	PopulationEstimates el = new PopulationEstimates();
    	this.populationEstimates = el;
    	return el;
    }

    /**
     * Creates a new empty {@link PrecisionPopulationEstimates} precisionPopulationEstimates element, adds it to the current object and returns it.
     * @return The created {@link PrecisionPopulationEstimates} object.
     */
    public PrecisionPopulationEstimates createPrecisionPopulationEstimates(){
    	PrecisionPopulationEstimates el = new PrecisionPopulationEstimates();
    	this.precisionPopulationEstimates = el;
    	return el;
    }

    /**
     * Creates a new empty {@link IndividualEstimates} individualEstimates element, adds it to the current object and returns it.
     * @return The created {@link IndividualEstimates} object.
     */
    public IndividualEstimates createIndividualEstimates(){
    	IndividualEstimates el = new IndividualEstimates();
    	this.individualEstimates = el;
    	return el;
    }

    /**
     * Creates a new empty {@link PrecisionIndividualEstimates} precisionIndividualEstimates element, adds it to the current object and returns it.
     * @return The created {@link PrecisionIndividualEstimates} object.
     */
    public PrecisionIndividualEstimates createPrecisionIndividualEstimates(){
    	PrecisionIndividualEstimates el = new PrecisionIndividualEstimates();
    	this.precisionIndividualEstimates = el;
    	return el;
    }

    /**
     * Creates a new empty {@link Residuals} residuals element, adds it to the current object and returns it.
     * @return The created {@link Residuals} object.
     */
    public Residuals createResiduals(){
    	Residuals el = new Residuals();
    	this.residuals = el;
    	return el;
    }

    /**
     * Creates a new empty {@link DataSetType} predictions element, adds it to the current object and returns it.
     * @return The created {@link DataSetType} object.
     */
    public DataSetType createPredictions(){
    	DataSetType el = new DataSetType();
    	this.predictions = el;
    	return el;
    }

    /**
     * Creates a new empty {@link Likelihood} likelihood element, adds it to the current object and returns it.
     * @return The created {@link Likelihood} object.
     */
    public Likelihood createLikelihood(){
    	Likelihood el = new Likelihood();
    	this.likelihood = el;
    	return el;
    }

    /**
     * Creates a new empty {@link TargetToolMessages} targetToolMessages element, adds it to the current object and returns it.
     * @return The created {@link TargetToolMessages} object.
     */
    public TargetToolMessages createTargetToolMessages(){
    	TargetToolMessages el = new TargetToolMessages();
    	this.targetToolMessages = el;
    	return el;
    }


}
