//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;


/**
 * Type defining the estimation part of the SO.
 * 
 * <p>Java class for EstimationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EstimationType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="PopulationEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PopulationEstimatesType" minOccurs="0"/>
 *         &lt;element name="PrecisionPopulationEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PrecisionPopulationEstimatesType" minOccurs="0"/>
 *         &lt;element name="IndividualEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}IndividualEstimatesType" minOccurs="0"/>
 *         &lt;element name="PrecisionIndividualEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PrecisionIndividualEstimatesType" minOccurs="0"/>
 *         &lt;element name="Residuals" type="{http://www.pharmml.org/2013/03/StandardisedOutput}ResidualsType" minOccurs="0"/>
 *         &lt;element name="Predictions" type="{http://www.pharmml.org/2013/03/StandardisedOutput}PredictionsType" minOccurs="0"/>
 *         &lt;element name="Likelihood" type="{http://www.pharmml.org/2013/03/StandardisedOutput}LikelihoodType" minOccurs="0"/>
 *         &lt;element name="TargetToolMessages" type="{http://www.pharmml.org/2013/03/StandardisedOutput}TargetToolMessagesType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EstimationType", propOrder = {
    "populationEstimates",
    "precisionPopulationEstimates",
    "individualEstimates",
    "precisionIndividualEstimates",
    "residuals",
    "predictions",
    "likelihood",
    "targetToolMessages"
})
public class Estimation
    extends PharmMLRootType
{

    @XmlElement(name = "PopulationEstimates")
    protected PopulationEstimates populationEstimates;
    @XmlElement(name = "PrecisionPopulationEstimates")
    protected PrecisionPopulationEstimates precisionPopulationEstimates;
    @XmlElement(name = "IndividualEstimates")
    protected IndividualEstimates individualEstimates;
    @XmlElement(name = "PrecisionIndividualEstimates")
    protected PrecisionIndividualEstimates precisionIndividualEstimates;
    @XmlElement(name = "Residuals")
    protected Residuals residuals;
    @XmlElement(name = "Predictions")
    protected Predictions predictions;
    @XmlElement(name = "Likelihood")
    protected Likelihood likelihood;
    @XmlElement(name = "TargetToolMessages")
    protected TargetToolMessages targetToolMessages;

    /**
     * Gets the value of the populationEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PopulationEstimates }
     *     
     */
    public PopulationEstimates getPopulationEstimates() {
        return populationEstimates;
    }

    /**
     * Sets the value of the populationEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopulationEstimates }
     *     
     */
    public void setPopulationEstimates(PopulationEstimates value) {
        this.populationEstimates = value;
    }

    /**
     * Gets the value of the precisionPopulationEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimates }
     *     
     */
    public PrecisionPopulationEstimates getPrecisionPopulationEstimates() {
        return precisionPopulationEstimates;
    }

    /**
     * Sets the value of the precisionPopulationEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimates }
     *     
     */
    public void setPrecisionPopulationEstimates(PrecisionPopulationEstimates value) {
        this.precisionPopulationEstimates = value;
    }

    /**
     * Gets the value of the individualEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimates }
     *     
     */
    public IndividualEstimates getIndividualEstimates() {
        return individualEstimates;
    }

    /**
     * Sets the value of the individualEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimates }
     *     
     */
    public void setIndividualEstimates(IndividualEstimates value) {
        this.individualEstimates = value;
    }

    /**
     * Gets the value of the precisionIndividualEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionIndividualEstimates }
     *     
     */
    public PrecisionIndividualEstimates getPrecisionIndividualEstimates() {
        return precisionIndividualEstimates;
    }

    /**
     * Sets the value of the precisionIndividualEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionIndividualEstimates }
     *     
     */
    public void setPrecisionIndividualEstimates(PrecisionIndividualEstimates value) {
        this.precisionIndividualEstimates = value;
    }

    /**
     * Gets the value of the residuals property.
     * 
     * @return
     *     possible object is
     *     {@link Residuals }
     *     
     */
    public Residuals getResiduals() {
        return residuals;
    }

    /**
     * Sets the value of the residuals property.
     * 
     * @param value
     *     allowed object is
     *     {@link Residuals }
     *     
     */
    public void setResiduals(Residuals value) {
        this.residuals = value;
    }

    /**
     * Gets the value of the predictions property.
     * 
     * @return
     *     possible object is
     *     {@link Predictions }
     *     
     */
    public Predictions getPredictions() {
        return predictions;
    }

    /**
     * Sets the value of the predictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Predictions }
     *     
     */
    public void setPredictions(Predictions value) {
        this.predictions = value;
    }

    /**
     * Gets the value of the likelihood property.
     * 
     * @return
     *     possible object is
     *     {@link Likelihood }
     *     
     */
    public Likelihood getLikelihood() {
        return likelihood;
    }

    /**
     * Sets the value of the likelihood property.
     * 
     * @param value
     *     allowed object is
     *     {@link Likelihood }
     *     
     */
    public void setLikelihood(Likelihood value) {
        this.likelihood = value;
    }

    /**
     * Gets the value of the targetToolMessages property.
     * 
     * @return
     *     possible object is
     *     {@link TargetToolMessages }
     *     
     */
    public TargetToolMessages getTargetToolMessages() {
        return targetToolMessages;
    }

    /**
     * Sets the value of the targetToolMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link TargetToolMessages }
     *     
     */
    public void setTargetToolMessages(TargetToolMessages value) {
        this.targetToolMessages = value;
    }

}
