/*******************************************************************************
 * Copyright (c) 2014 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 05:16:18 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSet;


/**
 * Type defining the individual estimates.
 * 
 * <p>Java class for IndividualEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="Estimates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="Mean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="Median" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="Mode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="Samples" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RandomEffects" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="EffectMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="EffectMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="EffectMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="Samples" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="EtaShrinkage" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualEstimatesType", propOrder = {
    "estimates",
    "randomEffects",
    "etaShrinkage"
})
public class IndividualEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "Estimates")
    protected IndividualEstimates.Estimates estimates;
    @XmlElement(name = "RandomEffects")
    protected IndividualEstimates.RandomEffects randomEffects;
    @XmlElement(name = "EtaShrinkage")
    protected DataSet etaShrinkage;

    /**
     * Gets the value of the estimates property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimatesType.Estimates }
     *     
     */
    public IndividualEstimates.Estimates getEstimates() {
        return estimates;
    }

    /**
     * Sets the value of the estimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimatesType.Estimates }
     *     
     */
    public void setEstimates(IndividualEstimates.Estimates value) {
        this.estimates = value;
    }

    /**
     * Gets the value of the randomEffects property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimatesType.RandomEffects }
     *     
     */
    public IndividualEstimates.RandomEffects getRandomEffects() {
        return randomEffects;
    }

    /**
     * Sets the value of the randomEffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimatesType.RandomEffects }
     *     
     */
    public void setRandomEffects(IndividualEstimates.RandomEffects value) {
        this.randomEffects = value;
    }

    /**
     * Gets the value of the etaShrinkage property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSet getEtaShrinkage() {
        return etaShrinkage;
    }

    /**
     * Sets the value of the etaShrinkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setEtaShrinkage(DataSet value) {
        this.etaShrinkage = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="Mean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="Median" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="Mode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="Samples" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "mean",
        "median",
        "mode",
        "samples"
    })
    public static class Estimates
        extends PharmMLRootType
    {

        @XmlElement(name = "Mean")
        protected DataSet mean;
        @XmlElement(name = "Median")
        protected DataSet median;
        @XmlElement(name = "Mode")
        protected DataSet mode;
        @XmlElement(name = "Samples")
        protected DataSet samples;

        /**
         * Gets the value of the mean property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSet getMean() {
            return mean;
        }

        /**
         * Sets the value of the mean property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setMean(DataSet value) {
            this.mean = value;
        }

        /**
         * Gets the value of the median property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSet getMedian() {
            return median;
        }

        /**
         * Sets the value of the median property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setMedian(DataSet value) {
            this.median = value;
        }

        /**
         * Gets the value of the mode property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSet getMode() {
            return mode;
        }

        /**
         * Sets the value of the mode property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSet }
         *     
         */
        public void setMode(DataSet value) {
            this.mode = value;
        }

        /**
         * Gets the value of the samples property.
         * 
         * @return
         *     possible object is
         *     {@link DataSet }
         *     
         */
        public DataSet getSamples() {
            return samples;
        }

        /**
         * Sets the value of the samples property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSet }
         *     
         */
        public void setSamples(DataSet value) {
            this.samples = value;
        }
        
        /**
         * Creates a new empty {@link DataSet} mean element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createMean(){
        	DataSet el = new DataSet();
        	this.mean = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} median element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createMedian(){
        	DataSet el = new DataSet();
        	this.median = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} mode element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createMode(){
        	DataSet el = new DataSet();
        	this.mode = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} samples element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createSamples(){
        	DataSet el = new DataSet();
        	this.samples = el;
        	return el;
        }


    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="EffectMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="EffectMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="EffectMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="Samples" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "effectMean",
        "effectMedian",
        "effectMode",
        "samples"
    })
    public static class RandomEffects
        extends PharmMLRootType
    {

        @XmlElement(name = "EffectMean")
        protected DataSet effectMean;
        @XmlElement(name = "EffectMedian")
        protected DataSet effectMedian;
        @XmlElement(name = "EffectMode")
        protected DataSet effectMode;
        @XmlElement(name = "Samples")
        protected DataSet samples;

        /**
         * Gets the value of the effectMean property.
         * 
         * @return
         *     possible object is
         *     {@link DataSet }
         *     
         */
        public DataSet getEffectMean() {
            return effectMean;
        }

        /**
         * Sets the value of the effectMean property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSet }
         *     
         */
        public void setEffectMean(DataSet value) {
            this.effectMean = value;
        }

        /**
         * Gets the value of the effectMedian property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSet getEffectMedian() {
            return effectMedian;
        }

        /**
         * Sets the value of the effectMedian property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setEffectMedian(DataSet value) {
            this.effectMedian = value;
        }

        /**
         * Gets the value of the effectMode property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSet getEffectMode() {
            return effectMode;
        }

        /**
         * Sets the value of the effectMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSet }
         *     
         */
        public void setEffectMode(DataSet value) {
            this.effectMode = value;
        }

        /**
         * Gets the value of the samples property.
         * 
         * @return
         *     possible object is
         *     {@link DataSet }
         *     
         */
        public DataSet getSamples() {
            return samples;
        }

        /**
         * Sets the value of the samples property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSet }
         *     
         */
        public void setSamples(DataSet value) {
            this.samples = value;
        }
        
        /**
         * Creates a new empty {@link DataSet} effectMean element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createEffectMean(){
        	DataSet el = new DataSet();
        	this.effectMean = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} effectMedian element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createEffectMedian(){
        	DataSet el = new DataSet();
        	this.effectMedian = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} effectMode element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createEffectMode(){
        	DataSet el = new DataSet();
        	this.effectMode = el;
        	return el;
        }

        /**
         * Creates a new empty {@link DataSet} samples element, adds it to the current object and returns it.
         * @return The created {@link DataSet} object.
         */
        public DataSet createSamples(){
        	DataSet el = new DataSet();
        	this.samples = el;
        	return el;
        }


    }

    /**
     * Creates a new empty {@link IndividualEstimates.Estimates} estimates element, adds it to the current object and returns it.
     * @return The created {@link IndividualEstimates.Estimates} object.
     */
    public IndividualEstimates.Estimates createEstimates(){
    	IndividualEstimates.Estimates el = new IndividualEstimates.Estimates();
    	this.estimates = el;
    	return el;
    }

    /**
     * Creates a new empty {@link IndividualEstimates.RandomEffects} randomEffects element, adds it to the current object and returns it.
     * @return The created {@link IndividualEstimates.RandomEffects} object.
     */
    public IndividualEstimates.RandomEffects createRandomEffects(){
    	IndividualEstimates.RandomEffects el = new IndividualEstimates.RandomEffects();
    	this.randomEffects = el;
    	return el;
    }

    /**
     * Creates a new empty {@link DataSet} etaShrinkage element, adds it to the current object and returns it.
     * @return The created {@link DataSet} object.
     */
    public DataSet createEtaShrinkage(){
    	DataSet el = new DataSet();
    	this.etaShrinkage = el;
    	return el;
    }

    
}
