//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 04:00:02 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the individual estimates.
 * 
 * <p>Java class for IndividualEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IndividualEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="MLE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="ConditionalEstimates" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="RandomEffects" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="EtaShrinkage" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bayesian" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="PosteriorEstimates" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                           &lt;sequence>
 *                             &lt;element name="PosteriorMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                             &lt;element name="PosteriorMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                             &lt;element name="PosteriorMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="PosteriorRandomEffects" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                           &lt;sequence>
 *                             &lt;element name="PosteriorEffectMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                             &lt;element name="PosteriorEffectMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                             &lt;element name="PosteriorEffectMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IndividualEstimatesType", propOrder = {
    "mle",
    "bayesian"
})
public class IndividualEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "MLE")
    protected IndividualEstimates.MLE mle;
    @XmlElement(name = "Bayesian")
    protected IndividualEstimates.Bayesian bayesian;

    /**
     * Gets the value of the mle property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimatesType.MLE }
     *     
     */
    public IndividualEstimates.MLE getMLE() {
        return mle;
    }

    /**
     * Sets the value of the mle property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimatesType.MLE }
     *     
     */
    public void setMLE(IndividualEstimates.MLE value) {
        this.mle = value;
    }

    /**
     * Gets the value of the bayesian property.
     * 
     * @return
     *     possible object is
     *     {@link IndividualEstimatesType.Bayesian }
     *     
     */
    public IndividualEstimates.Bayesian getBayesian() {
        return bayesian;
    }

    /**
     * Sets the value of the bayesian property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndividualEstimatesType.Bayesian }
     *     
     */
    public void setBayesian(IndividualEstimates.Bayesian value) {
        this.bayesian = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="PosteriorEstimates" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *                 &lt;sequence>
     *                   &lt;element name="PosteriorMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                   &lt;element name="PosteriorMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                   &lt;element name="PosteriorMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="PosteriorRandomEffects" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *                 &lt;sequence>
     *                   &lt;element name="PosteriorEffectMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                   &lt;element name="PosteriorEffectMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                   &lt;element name="PosteriorEffectMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "posteriorEstimates",
        "posteriorRandomEffects"
    })
    public static class Bayesian
        extends PharmMLRootType
    {

        @XmlElement(name = "PosteriorEstimates")
        protected IndividualEstimates.Bayesian.PosteriorEstimates posteriorEstimates;
        @XmlElement(name = "PosteriorRandomEffects")
        protected IndividualEstimates.Bayesian.PosteriorRandomEffects posteriorRandomEffects;

        /**
         * Gets the value of the posteriorEstimates property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualEstimatesType.Bayesian.PosteriorEstimates }
         *     
         */
        public IndividualEstimates.Bayesian.PosteriorEstimates getPosteriorEstimates() {
            return posteriorEstimates;
        }

        /**
         * Sets the value of the posteriorEstimates property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualEstimatesType.Bayesian.PosteriorEstimates }
         *     
         */
        public void setPosteriorEstimates(IndividualEstimates.Bayesian.PosteriorEstimates value) {
            this.posteriorEstimates = value;
        }

        /**
         * Gets the value of the posteriorRandomEffects property.
         * 
         * @return
         *     possible object is
         *     {@link IndividualEstimatesType.Bayesian.PosteriorRandomEffects }
         *     
         */
        public IndividualEstimates.Bayesian.PosteriorRandomEffects getPosteriorRandomEffects() {
            return posteriorRandomEffects;
        }

        /**
         * Sets the value of the posteriorRandomEffects property.
         * 
         * @param value
         *     allowed object is
         *     {@link IndividualEstimatesType.Bayesian.PosteriorRandomEffects }
         *     
         */
        public void setPosteriorRandomEffects(IndividualEstimates.Bayesian.PosteriorRandomEffects value) {
            this.posteriorRandomEffects = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
         *       &lt;sequence>
         *         &lt;element name="PosteriorMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *         &lt;element name="PosteriorMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *         &lt;element name="PosteriorMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "posteriorMean",
            "posteriorMedian",
            "posteriorMode"
        })
        public static class PosteriorEstimates
            extends PharmMLRootType
        {

            @XmlElement(name = "PosteriorMean")
            protected DataSetType posteriorMean;
            @XmlElement(name = "PosteriorMedian")
            protected DataSetType posteriorMedian;
            @XmlElement(name = "PosteriorMode")
            protected DataSetType posteriorMode;

            /**
             * Gets the value of the posteriorMean property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorMean() {
                return posteriorMean;
            }

            /**
             * Sets the value of the posteriorMean property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorMean(DataSetType value) {
                this.posteriorMean = value;
            }

            /**
             * Gets the value of the posteriorMedian property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorMedian() {
                return posteriorMedian;
            }

            /**
             * Sets the value of the posteriorMedian property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorMedian(DataSetType value) {
                this.posteriorMedian = value;
            }

            /**
             * Gets the value of the posteriorMode property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorMode() {
                return posteriorMode;
            }

            /**
             * Sets the value of the posteriorMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorMode(DataSetType value) {
                this.posteriorMode = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
         *       &lt;sequence>
         *         &lt;element name="PosteriorEffectMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *         &lt;element name="PosteriorEffectMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *         &lt;element name="PosteriorEffectMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "posteriorEffectMean",
            "posteriorEffectMedian",
            "posteriorEffectMode"
        })
        public static class PosteriorRandomEffects
            extends PharmMLRootType
        {

            @XmlElement(name = "PosteriorEffectMean")
            protected DataSetType posteriorEffectMean;
            @XmlElement(name = "PosteriorEffectMedian")
            protected DataSetType posteriorEffectMedian;
            @XmlElement(name = "PosteriorEffectMode")
            protected DataSetType posteriorEffectMode;

            /**
             * Gets the value of the posteriorEffectMean property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorEffectMean() {
                return posteriorEffectMean;
            }

            /**
             * Sets the value of the posteriorEffectMean property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorEffectMean(DataSetType value) {
                this.posteriorEffectMean = value;
            }

            /**
             * Gets the value of the posteriorEffectMedian property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorEffectMedian() {
                return posteriorEffectMedian;
            }

            /**
             * Sets the value of the posteriorEffectMedian property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorEffectMedian(DataSetType value) {
                this.posteriorEffectMedian = value;
            }

            /**
             * Gets the value of the posteriorEffectMode property.
             * 
             * @return
             *     possible object is
             *     {@link DataSetType }
             *     
             */
            public DataSetType getPosteriorEffectMode() {
                return posteriorEffectMode;
            }

            /**
             * Sets the value of the posteriorEffectMode property.
             * 
             * @param value
             *     allowed object is
             *     {@link DataSetType }
             *     
             */
            public void setPosteriorEffectMode(DataSetType value) {
                this.posteriorEffectMode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="ConditionalEstimates" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="RandomEffects" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="EtaShrinkage" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "conditionalEstimates",
        "randomEffects",
        "etaShrinkage"
    })
    public static class MLE
        extends PharmMLRootType
    {

        @XmlElement(name = "ConditionalEstimates")
        protected DataSetType conditionalEstimates;
        @XmlElement(name = "RandomEffects")
        protected DataSetType randomEffects;
        @XmlElement(name = "EtaShrinkage")
        protected DataSetType etaShrinkage;

        /**
         * Gets the value of the conditionalEstimates property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getConditionalEstimates() {
            return conditionalEstimates;
        }

        /**
         * Sets the value of the conditionalEstimates property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setConditionalEstimates(DataSetType value) {
            this.conditionalEstimates = value;
        }

        /**
         * Gets the value of the randomEffects property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getRandomEffects() {
            return randomEffects;
        }

        /**
         * Sets the value of the randomEffects property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setRandomEffects(DataSetType value) {
            this.randomEffects = value;
        }

        /**
         * Gets the value of the etaShrinkage property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getEtaShrinkage() {
            return etaShrinkage;
        }

        /**
         * Sets the value of the etaShrinkage property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setEtaShrinkage(DataSetType value) {
            this.etaShrinkage = value;
        }

    }

}
