//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 11:14:40 AM GMT 
//


package eu.ddmore.libpharmml.so.dom;

import java.util.ArrayList;
import java.util.List;

import javax.swing.tree.TreeNode;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSet;
import eu.ddmore.libpharmml.util.ChainedList;


/**
 * Type for the model diagnostic
 * 
 * <p>Java class for ModelDiagnosticType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ModelDiagnosticType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.pharmml.org/pharmml/0.6/CommonTypes}PharmMLRootType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="DiagnosticPlotsStructuralModel" type="{http://www.pharmml.org/so/0.1/StandardisedOutput}DiagnosticPlotsStructuralModelType" minOccurs="0"/&gt;
 *           &lt;element name="DiagnosticPlotsIndividualParams" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ModelDiagnosticType", propOrder = {
    "diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams"
})
public class ModelDiagnostic
    extends PharmMLRootType
{

    @XmlElements({
        @XmlElement(name = "DiagnosticPlotsStructuralModel", type = DiagnosticPlotsStructuralModel.class),
        @XmlElement(name = "DiagnosticPlotsIndividualParams", type = DataSet.class)
    })
    protected List<PharmMLRootType> diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams;

    /**
     * Gets the value of the diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDiagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DiagnosticPlotsStructuralModel }
     * {@link DataSet }
     * 
     * 
     */
    public List<PharmMLRootType> getDiagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams() {
        if (diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams == null) {
            diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams = new ArrayList<PharmMLRootType>();
        }
        return this.diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams;
    }
    
    @Override
    protected List<TreeNode> listChildren() {
    	return new ChainedList<TreeNode>(super.listChildren())
    			.addIfNotNull(diagnosticPlotsStructuralModelsAndDiagnosticPlotsIndividualParams);
    }

}
