//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the population estimates.
 * 
 * <p>Java class for PopulationEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PopulationEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="MLEEstimates" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="BayesianEstimates" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="PosteriorMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="PosteriorMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="PosteriorMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PopulationEstimatesType", propOrder = {
    "mleEstimates",
    "bayesianEstimates"
})
public class PopulationEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "MLEEstimates")
    protected DataSetType mleEstimates;
    @XmlElement(name = "BayesianEstimates")
    protected PopulationEstimates.BayesianEstimates bayesianEstimates;

    /**
     * Gets the value of the mleEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getMLEEstimates() {
        return mleEstimates;
    }

    /**
     * Sets the value of the mleEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setMLEEstimates(DataSetType value) {
        this.mleEstimates = value;
    }

    /**
     * Gets the value of the bayesianEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link PopulationEstimates.BayesianEstimates }
     *     
     */
    public PopulationEstimates.BayesianEstimates getBayesianEstimates() {
        return bayesianEstimates;
    }

    /**
     * Sets the value of the bayesianEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link PopulationEstimates.BayesianEstimates }
     *     
     */
    public void setBayesianEstimates(PopulationEstimates.BayesianEstimates value) {
        this.bayesianEstimates = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="PosteriorMean" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="PosteriorMedian" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="PosteriorMode" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "posteriorMean",
        "posteriorMedian",
        "posteriorMode"
    })
    public static class BayesianEstimates
        extends PharmMLRootType
    {

        @XmlElement(name = "PosteriorMean")
        protected DataSetType posteriorMean;
        @XmlElement(name = "PosteriorMedian")
        protected DataSetType posteriorMedian;
        @XmlElement(name = "PosteriorMode")
        protected DataSetType posteriorMode;

        /**
         * Gets the value of the posteriorMean property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getPosteriorMean() {
            return posteriorMean;
        }

        /**
         * Sets the value of the posteriorMean property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setPosteriorMean(DataSetType value) {
            this.posteriorMean = value;
        }

        /**
         * Gets the value of the posteriorMedian property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getPosteriorMedian() {
            return posteriorMedian;
        }

        /**
         * Sets the value of the posteriorMedian property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setPosteriorMedian(DataSetType value) {
            this.posteriorMedian = value;
        }

        /**
         * Gets the value of the posteriorMode property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getPosteriorMode() {
            return posteriorMode;
        }

        /**
         * Sets the value of the posteriorMode property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setPosteriorMode(DataSetType value) {
            this.posteriorMode = value;
        }

    }

}
