//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 11:14:40 AM GMT 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSet;


/**
 * Combined type for other population estimates
 * 
 * <p>Java class for PrecisionEstimatesPercentileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecisionEstimatesPercentileType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/pharmml/0.6/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="PrecisionEstimates" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType"/>
 *         &lt;element name="Percentiles" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType"/>
 *         &lt;element name="PosteriorDistribution" type="{http://www.pharmml.org/so/0.2/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecisionEstimatesPercentileType", propOrder = {
    "precisionEstimates",
    "percentiles",
    "posteriorDistribution"
})
public class PrecisionEstimatesPercentile
    extends PharmMLRootType
{

    @XmlElement(name = "PrecisionEstimates", required = true)
    protected DataSet precisionEstimates;
    @XmlElement(name = "Percentiles", required = true)
    protected DataSet percentiles;
    @XmlElement(name = "PosteriorDistribution")
    protected SOTableDistrib posteriorDistribution;

    /**
     * Gets the value of the precisionEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getPrecisionEstimates() {
        return precisionEstimates;
    }

    /**
     * Sets the value of the precisionEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setPrecisionEstimates(DataSet value) {
        this.precisionEstimates = value;
    }

    /**
     * Gets the value of the percentiles property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getPercentiles() {
        return percentiles;
    }

    /**
     * Sets the value of the percentiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setPercentiles(DataSet value) {
        this.percentiles = value;
    }

    /**
     * Gets the value of the posteriorDistribution property.
     * 
     * @return
     *     possible object is
     *     {@link SOTableDistribType }
     *     
     */
    public SOTableDistrib getPosteriorDistribution() {
        return posteriorDistribution;
    }

    /**
     * Sets the value of the posteriorDistribution property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOTableDistribType }
     *     
     */
    public void setPosteriorDistribution(SOTableDistrib value) {
        this.posteriorDistribution = value;
    }

}
