//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 04:00:02 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;


/**
 * Type defining the precision individual estimates.
 * 
 * <p>Java class for PrecisionIndividualEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecisionIndividualEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="PosteriorDistributionIndividualEstimates" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecisionIndividualEstimatesType", propOrder = {
    "posteriorDistributionIndividualEstimates"
})
public class PrecisionIndividualEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "PosteriorDistributionIndividualEstimates")
    protected SOTableDistrib posteriorDistributionIndividualEstimates;

    /**
     * Gets the value of the posteriorDistributionIndividualEstimates property.
     * 
     * @return
     *     possible object is
     *     {@link SOTableDistribType }
     *     
     */
    public SOTableDistrib getPosteriorDistributionIndividualEstimates() {
        return posteriorDistributionIndividualEstimates;
    }

    /**
     * Sets the value of the posteriorDistributionIndividualEstimates property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOTableDistribType }
     *     
     */
    public void setPosteriorDistributionIndividualEstimates(SOTableDistrib value) {
        this.posteriorDistributionIndividualEstimates = value;
    }
    
    /**
     * Creates a new empty {@link SOTableDistrib} posteriorDistributionIndividualEstimates element, adds it to the current object and returns it.
     * @return The created {@link SOTableDistrib} object.
     */
    public SOTableDistrib createPosteriorDistributionIndividualEstimates(){
    	SOTableDistrib el = new SOTableDistrib();
    	this.posteriorDistributionIndividualEstimates = el;
    	return el;
    }


}
