//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the precision population estimates.
 * 
 * 
 *                         First level of the precision of population estimates.
 *                     
 * 
 * <p>Java class for PrecisionPopulationEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecisionPopulationEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="MLE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="FIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="InverseFIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="CorrelationMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="StandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="RelativeStandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bayesian" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="StandardDeviationPosterior" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="PosteriorDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bootstrap" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="StandardDeviation" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="ParameterDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ConfidenceInterval" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecisionPopulationEstimatesType", propOrder = {
    "mle",
    "bayesian",
    "bootstrap",
    "confidenceInterval"
})
public class PrecisionPopulationEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "MLE")
    protected PrecisionPopulationEstimates.MLE mle;
    @XmlElement(name = "Bayesian")
    protected PrecisionPopulationEstimates.Bayesian bayesian;
    @XmlElement(name = "Bootstrap")
    protected PrecisionPopulationEstimates.Bootstrap bootstrap;
    @XmlElement(name = "ConfidenceInterval")
    protected DataSetType confidenceInterval;

    /**
     * Gets the value of the mle property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimates.MLE }
     *     
     */
    public PrecisionPopulationEstimates.MLE getMLE() {
        return mle;
    }

    /**
     * Sets the value of the mle property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimates.MLE }
     *     
     */
    public void setMLE(PrecisionPopulationEstimates.MLE value) {
        this.mle = value;
    }

    /**
     * Gets the value of the bayesian property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimates.Bayesian }
     *     
     */
    public PrecisionPopulationEstimates.Bayesian getBayesian() {
        return bayesian;
    }

    /**
     * Sets the value of the bayesian property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimates.Bayesian }
     *     
     */
    public void setBayesian(PrecisionPopulationEstimates.Bayesian value) {
        this.bayesian = value;
    }

    /**
     * Gets the value of the bootstrap property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimates.Bootstrap }
     *     
     */
    public PrecisionPopulationEstimates.Bootstrap getBootstrap() {
        return bootstrap;
    }

    /**
     * Sets the value of the bootstrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimates.Bootstrap }
     *     
     */
    public void setBootstrap(PrecisionPopulationEstimates.Bootstrap value) {
        this.bootstrap = value;
    }

    /**
     * Gets the value of the confidenceInterval property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getConfidenceInterval() {
        return confidenceInterval;
    }

    /**
     * Sets the value of the confidenceInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setConfidenceInterval(DataSetType value) {
        this.confidenceInterval = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="StandardDeviationPosterior" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="PosteriorDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "standardDeviationPosterior",
        "posteriorDistribution"
    })
    public static class Bayesian
        extends PharmMLRootType
    {

        @XmlElement(name = "StandardDeviationPosterior")
        protected DataSetType standardDeviationPosterior;
        @XmlElement(name = "PosteriorDistribution")
        protected SOTableDistrib posteriorDistribution;

        /**
         * Gets the value of the standardDeviationPosterior property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardDeviationPosterior() {
            return standardDeviationPosterior;
        }

        /**
         * Sets the value of the standardDeviationPosterior property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardDeviationPosterior(DataSetType value) {
            this.standardDeviationPosterior = value;
        }

        /**
         * Gets the value of the posteriorDistribution property.
         * 
         * @return
         *     possible object is
         *     {@link SOTableDistrib }
         *     
         */
        public SOTableDistrib getPosteriorDistribution() {
            return posteriorDistribution;
        }

        /**
         * Sets the value of the posteriorDistribution property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOTableDistrib }
         *     
         */
        public void setPosteriorDistribution(SOTableDistrib value) {
            this.posteriorDistribution = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="StandardDeviation" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="ParameterDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "standardDeviation",
        "parameterDistribution"
    })
    public static class Bootstrap
        extends PharmMLRootType
    {

        @XmlElement(name = "StandardDeviation")
        protected DataSetType standardDeviation;
        @XmlElement(name = "ParameterDistribution")
        protected SOTableDistrib parameterDistribution;

        /**
         * Gets the value of the standardDeviation property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardDeviation() {
            return standardDeviation;
        }

        /**
         * Sets the value of the standardDeviation property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardDeviation(DataSetType value) {
            this.standardDeviation = value;
        }

        /**
         * Gets the value of the parameterDistribution property.
         * 
         * @return
         *     possible object is
         *     {@link SOTableDistrib }
         *     
         */
        public SOTableDistrib getParameterDistribution() {
            return parameterDistribution;
        }

        /**
         * Sets the value of the parameterDistribution property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOTableDistrib }
         *     
         */
        public void setParameterDistribution(SOTableDistrib value) {
            this.parameterDistribution = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="FIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="InverseFIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="CorrelationMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="StandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="RelativeStandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fim",
        "inverseFIM",
        "correlationMatrix",
        "standardError",
        "relativeStandardError"
    })
    public static class MLE
        extends PharmMLRootType
    {

        @XmlElement(name = "FIM")
        protected SOMatrix fim;
        @XmlElement(name = "InverseFIM")
        protected SOMatrix inverseFIM;
        @XmlElement(name = "CorrelationMatrix")
        protected SOMatrix correlationMatrix;
        @XmlElement(name = "StandardError")
        protected DataSetType standardError;
        @XmlElement(name = "RelativeStandardError")
        protected DataSetType relativeStandardError;

        /**
         * Gets the value of the fim property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrix }
         *     
         */
        public SOMatrix getFIM() {
            return fim;
        }

        /**
         * Sets the value of the fim property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrix }
         *     
         */
        public void setFIM(SOMatrix value) {
            this.fim = value;
        }

        /**
         * Gets the value of the inverseFIM property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrix }
         *     
         */
        public SOMatrix getInverseFIM() {
            return inverseFIM;
        }

        /**
         * Sets the value of the inverseFIM property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrix }
         *     
         */
        public void setInverseFIM(SOMatrix value) {
            this.inverseFIM = value;
        }

        /**
         * Gets the value of the correlationMatrix property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrix }
         *     
         */
        public SOMatrix getCorrelationMatrix() {
            return correlationMatrix;
        }

        /**
         * Sets the value of the correlationMatrix property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrix }
         *     
         */
        public void setCorrelationMatrix(SOMatrix value) {
            this.correlationMatrix = value;
        }

        /**
         * Gets the value of the standardError property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardError() {
            return standardError;
        }

        /**
         * Sets the value of the standardError property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardError(DataSetType value) {
            this.standardError = value;
        }

        /**
         * Gets the value of the relativeStandardError property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getRelativeStandardError() {
            return relativeStandardError;
        }

        /**
         * Sets the value of the relativeStandardError property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setRelativeStandardError(DataSetType value) {
            this.relativeStandardError = value;
        }

    }

}
