//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.17 at 04:00:02 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the precision population estimates.
 * 
 * 
 *                         First level of the precision of population estimates.
 *                     
 * 
 * <p>Java class for PrecisionPopulationEstimatesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrecisionPopulationEstimatesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="MLE" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="FIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="CovarianceMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="CorrelationMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
 *                   &lt;element name="StandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="RelativeStandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="AsymptoticCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bayesian" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="StandardDeviationPosterior" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="PosteriorDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *                   &lt;element name="PercentilesCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Bootstrap" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *                 &lt;sequence>
 *                   &lt;element name="StandardDeviation" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                   &lt;element name="ParameterDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
 *                   &lt;element name="PercentilesCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrecisionPopulationEstimatesType", propOrder = {
    "mle",
    "bayesian",
    "bootstrap"
})
public class PrecisionPopulationEstimates
    extends PharmMLRootType
{

    @XmlElement(name = "MLE")
    protected PrecisionPopulationEstimates.MLE mle;
    @XmlElement(name = "Bayesian")
    protected PrecisionPopulationEstimates.Bayesian bayesian;
    @XmlElement(name = "Bootstrap")
    protected PrecisionPopulationEstimates.Bootstrap bootstrap;

    /**
     * Gets the value of the mle property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimatesType.MLE }
     *     
     */
    public PrecisionPopulationEstimates.MLE getMLE() {
        return mle;
    }

    /**
     * Sets the value of the mle property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimatesType.MLE }
     *     
     */
    public void setMLE(PrecisionPopulationEstimates.MLE value) {
        this.mle = value;
    }

    /**
     * Gets the value of the bayesian property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimatesType.Bayesian }
     *     
     */
    public PrecisionPopulationEstimates.Bayesian getBayesian() {
        return bayesian;
    }

    /**
     * Sets the value of the bayesian property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimatesType.Bayesian }
     *     
     */
    public void setBayesian(PrecisionPopulationEstimates.Bayesian value) {
        this.bayesian = value;
    }

    /**
     * Gets the value of the bootstrap property.
     * 
     * @return
     *     possible object is
     *     {@link PrecisionPopulationEstimatesType.Bootstrap }
     *     
     */
    public PrecisionPopulationEstimates.Bootstrap getBootstrap() {
        return bootstrap;
    }

    /**
     * Sets the value of the bootstrap property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrecisionPopulationEstimatesType.Bootstrap }
     *     
     */
    public void setBootstrap(PrecisionPopulationEstimates.Bootstrap value) {
        this.bootstrap = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="StandardDeviationPosterior" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="PosteriorDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
     *         &lt;element name="QuantilesCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "standardDeviationPosterior",
        "posteriorDistribution",
        "percentilesCI"
    })
    public static class Bayesian
        extends PharmMLRootType
    {

        @XmlElement(name = "StandardDeviationPosterior")
        protected DataSetType standardDeviationPosterior;
        @XmlElement(name = "PosteriorDistribution")
        protected SOTableDistrib posteriorDistribution;
        @XmlElement(name = "PercentilesCI")
        protected DataSetType percentilesCI;

        /**
         * Gets the value of the standardDeviationPosterior property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardDeviationPosterior() {
            return standardDeviationPosterior;
        }

        /**
         * Sets the value of the standardDeviationPosterior property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardDeviationPosterior(DataSetType value) {
            this.standardDeviationPosterior = value;
        }

        /**
         * Gets the value of the posteriorDistribution property.
         * 
         * @return
         *     possible object is
         *     {@link SOTableDistribType }
         *     
         */
        public SOTableDistrib getPosteriorDistribution() {
            return posteriorDistribution;
        }

        /**
         * Sets the value of the posteriorDistribution property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOTableDistribType }
         *     
         */
        public void setPosteriorDistribution(SOTableDistrib value) {
            this.posteriorDistribution = value;
        }

        /**
         * Gets the value of the percentilesCI property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getPercentilesCI() {
            return percentilesCI;
        }

        /**
         * Sets the value of the percentilesCI property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setPercentilesCI(DataSetType value) {
            this.percentilesCI = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="StandardDeviation" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="ParameterDistribution" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOTableDistribType" minOccurs="0"/>
     *         &lt;element name="PercentilesCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "standardDeviation",
        "parameterDistribution",
        "percentilesCI"
    })
    public static class Bootstrap
        extends PharmMLRootType
    {

        @XmlElement(name = "StandardDeviation")
        protected DataSetType standardDeviation;
        @XmlElement(name = "ParameterDistribution")
        protected SOTableDistrib parameterDistribution;
        @XmlElement(name = "PercentilesCI")
        protected DataSetType percentilesCI;

        /**
         * Gets the value of the standardDeviation property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardDeviation() {
            return standardDeviation;
        }

        /**
         * Sets the value of the standardDeviation property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardDeviation(DataSetType value) {
            this.standardDeviation = value;
        }

        /**
         * Gets the value of the parameterDistribution property.
         * 
         * @return
         *     possible object is
         *     {@link SOTableDistribType }
         *     
         */
        public SOTableDistrib getParameterDistribution() {
            return parameterDistribution;
        }

        /**
         * Sets the value of the parameterDistribution property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOTableDistribType }
         *     
         */
        public void setParameterDistribution(SOTableDistrib value) {
            this.parameterDistribution = value;
        }

        /**
         * Gets the value of the percentilesCI property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getPercentilesCI() {
            return percentilesCI;
        }

        /**
         * Sets the value of the percentilesCI property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setPercentilesCI(DataSetType value) {
            this.percentilesCI = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
     *       &lt;sequence>
     *         &lt;element name="FIM" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="CovarianceMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="CorrelationMatrix" type="{http://www.pharmml.org/2013/03/StandardisedOutput}SOMatrixType" minOccurs="0"/>
     *         &lt;element name="StandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="RelativeStandardError" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *         &lt;element name="AsymptoticCI" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fim",
        "covarianceMatrix",
        "correlationMatrix",
        "standardError",
        "relativeStandardError",
        "asymptoticCI"
    })
    public static class MLE
        extends PharmMLRootType
    {

        @XmlElement(name = "FIM")
        protected SOMatrix fim;
        @XmlElement(name = "CovarianceMatrix")
        protected SOMatrix covarianceMatrix;
        @XmlElement(name = "CorrelationMatrix")
        protected SOMatrix correlationMatrix;
        @XmlElement(name = "StandardError")
        protected DataSetType standardError;
        @XmlElement(name = "RelativeStandardError")
        protected DataSetType relativeStandardError;
        @XmlElement(name = "AsymptoticCI")
        protected DataSetType asymptoticCI;

        /**
         * Gets the value of the fim property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrixType }
         *     
         */
        public SOMatrix getFIM() {
            return fim;
        }

        /**
         * Sets the value of the fim property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrixType }
         *     
         */
        public void setFIM(SOMatrix value) {
            this.fim = value;
        }

        /**
         * Gets the value of the covarianceMatrix property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrixType }
         *     
         */
        public SOMatrix getCovarianceMatrix() {
            return covarianceMatrix;
        }

        /**
         * Sets the value of the covarianceMatrix property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrixType }
         *     
         */
        public void setCovarianceMatrix(SOMatrix value) {
            this.covarianceMatrix = value;
        }

        /**
         * Gets the value of the correlationMatrix property.
         * 
         * @return
         *     possible object is
         *     {@link SOMatrixType }
         *     
         */
        public SOMatrix getCorrelationMatrix() {
            return correlationMatrix;
        }

        /**
         * Sets the value of the correlationMatrix property.
         * 
         * @param value
         *     allowed object is
         *     {@link SOMatrixType }
         *     
         */
        public void setCorrelationMatrix(SOMatrix value) {
            this.correlationMatrix = value;
        }

        /**
         * Gets the value of the standardError property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getStandardError() {
            return standardError;
        }

        /**
         * Sets the value of the standardError property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setStandardError(DataSetType value) {
            this.standardError = value;
        }

        /**
         * Gets the value of the relativeStandardError property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getRelativeStandardError() {
            return relativeStandardError;
        }

        /**
         * Sets the value of the relativeStandardError property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setRelativeStandardError(DataSetType value) {
            this.relativeStandardError = value;
        }

        /**
         * Gets the value of the asymptoticCI property.
         * 
         * @return
         *     possible object is
         *     {@link DataSetType }
         *     
         */
        public DataSetType getAsymptoticCI() {
            return asymptoticCI;
        }

        /**
         * Sets the value of the asymptoticCI property.
         * 
         * @param value
         *     allowed object is
         *     {@link DataSetType }
         *     
         */
        public void setAsymptoticCI(DataSetType value) {
            this.asymptoticCI = value;
        }

    }

}
