//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSetType;


/**
 * Type defining the residuals.
 * 
 * <p>Java class for ResidualsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResidualsType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="RES" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="IRES" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="WRES" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="CWRES" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="IWRES" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="PD" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *         &lt;element name="NPDE" type="{http://www.pharmml.org/2013/08/Dataset}DataSetType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResidualsType", propOrder = {
    "res",
    "ires",
    "wres",
    "cwres",
    "iwres",
    "pd",
    "npde"
})
public class Residuals
    extends PharmMLRootType
{

    @XmlElement(name = "RES")
    protected DataSetType res;
    @XmlElement(name = "IRES")
    protected DataSetType ires;
    @XmlElement(name = "WRES")
    protected DataSetType wres;
    @XmlElement(name = "CWRES")
    protected DataSetType cwres;
    @XmlElement(name = "IWRES")
    protected DataSetType iwres;
    @XmlElement(name = "PD")
    protected DataSetType pd;
    @XmlElement(name = "NPDE")
    protected DataSetType npde;

    /**
     * Gets the value of the res property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getRES() {
        return res;
    }

    /**
     * Sets the value of the res property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setRES(DataSetType value) {
        this.res = value;
    }

    /**
     * Gets the value of the ires property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getIRES() {
        return ires;
    }

    /**
     * Sets the value of the ires property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setIRES(DataSetType value) {
        this.ires = value;
    }

    /**
     * Gets the value of the wres property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getWRES() {
        return wres;
    }

    /**
     * Sets the value of the wres property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setWRES(DataSetType value) {
        this.wres = value;
    }

    /**
     * Gets the value of the cwres property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getCWRES() {
        return cwres;
    }

    /**
     * Sets the value of the cwres property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setCWRES(DataSetType value) {
        this.cwres = value;
    }

    /**
     * Gets the value of the iwres property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getIWRES() {
        return iwres;
    }

    /**
     * Sets the value of the iwres property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setIWRES(DataSetType value) {
        this.iwres = value;
    }

    /**
     * Gets the value of the pd property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getPD() {
        return pd;
    }

    /**
     * Sets the value of the pd property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setPD(DataSetType value) {
        this.pd = value;
    }

    /**
     * Gets the value of the npde property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetType }
     *     
     */
    public DataSetType getNPDE() {
        return npde;
    }

    /**
     * Sets the value of the npde property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetType }
     *     
     */
    public void setNPDE(DataSetType value) {
        this.npde = value;
    }

}
