//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 11:14:40 AM GMT 
//


package eu.ddmore.libpharmml.so.dom;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.DataSet;
import eu.ddmore.libpharmml.dom.dataset.ExternalFile;


/**
 * Type for the simulation block for on ereplicate.
 * 
 * <p>Java class for SimulationBlockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SimulationBlockType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.pharmml.org/pharmml/0.6/CommonTypes}PharmMLRootType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SimulatedProfiles" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="IndivParameters" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="RandomEffects" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="Covariates" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="PopulationParameters" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="Dosing" type="{http://www.pharmml.org/pharmml/0.6/Dataset}DataSetType" minOccurs="0"/&gt;
 *         &lt;element name="RawResultsFile" type="{http://www.pharmml.org/pharmml/0.6/Dataset}ExternalFileType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="replicate" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SimulationBlockType", propOrder = {
    "simulatedProfiles",
    "indivParameters",
    "randomEffects",
    "covariates",
    "populationParameters",
    "dosing",
    "rawResultsFile"
})
public class SimulationBlock
    extends PharmMLRootType
{

    @XmlElement(name = "SimulatedProfiles")
    protected DataSet simulatedProfiles;
    @XmlElement(name = "IndivParameters")
    protected DataSet indivParameters;
    @XmlElement(name = "RandomEffects")
    protected DataSet randomEffects;
    @XmlElement(name = "Covariates")
    protected DataSet covariates;
    @XmlElement(name = "PopulationParameters")
    protected DataSet populationParameters;
    @XmlElement(name = "Dosing")
    protected DataSet dosing;
    @XmlElement(name = "RawResultsFile")
    protected ExternalFile rawResultsFile;
    @XmlAttribute(name = "replicate")
    protected BigInteger replicate;

    /**
     * Gets the value of the simulatedProfiles property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getSimulatedProfiles() {
        return simulatedProfiles;
    }

    /**
     * Sets the value of the simulatedProfiles property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setSimulatedProfiles(DataSet value) {
        this.simulatedProfiles = value;
    }

    /**
     * Gets the value of the indivParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getIndivParameters() {
        return indivParameters;
    }

    /**
     * Sets the value of the indivParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setIndivParameters(DataSet value) {
        this.indivParameters = value;
    }

    /**
     * Gets the value of the randomEffects property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getRandomEffects() {
        return randomEffects;
    }

    /**
     * Sets the value of the randomEffects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setRandomEffects(DataSet value) {
        this.randomEffects = value;
    }

    /**
     * Gets the value of the covariates property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getCovariates() {
        return covariates;
    }

    /**
     * Sets the value of the covariates property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setCovariates(DataSet value) {
        this.covariates = value;
    }

    /**
     * Gets the value of the populationParameters property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getPopulationParameters() {
        return populationParameters;
    }

    /**
     * Sets the value of the populationParameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setPopulationParameters(DataSet value) {
        this.populationParameters = value;
    }

    /**
     * Gets the value of the dosing property.
     * 
     * @return
     *     possible object is
     *     {@link DataSet }
     *     
     */
    public DataSet getDosing() {
        return dosing;
    }

    /**
     * Sets the value of the dosing property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSet }
     *     
     */
    public void setDosing(DataSet value) {
        this.dosing = value;
    }

    /**
     * Gets the value of the rawResultsFile property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalFile }
     *     
     */
    public ExternalFile getRawResultsFile() {
        return rawResultsFile;
    }

    /**
     * Sets the value of the rawResultsFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalFile }
     *     
     */
    public void setRawResultsFile(ExternalFile value) {
        this.rawResultsFile = value;
    }

    /**
     * Gets the value of the replicate property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getReplicate() {
        return replicate;
    }

    /**
     * Sets the value of the replicate property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setReplicate(BigInteger value) {
        this.replicate = value;
    }

}
