/*******************************************************************************
 * Copyright (c) 2014 European Molecular Biology Laboratory,
 * Heidelberg, Germany.
 *
 * Licensed under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in
 * compliance with the License.  You may obtain a copy of
 * the License at
 *
 * 		http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, 
 * software distributed under the License is distributed on 
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY 
 * KIND, either express or implied. See the License for the 
 * specific language governing permissions and limitations 
 * under the License.
 *******************************************************************************/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.ExternalFile;


/**
 * A type defining the SO block.
 * 
 * <p>Java class for SOBlockType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SOBlockType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="ToolSettings" type="{http://www.pharmml.org/2013/08/Dataset}ExternalFile" minOccurs="0"/>
 *         &lt;element name="RawResults" type="{http://www.pharmml.org/2013/03/StandardisedOutput}RawResultsType" minOccurs="0"/>
 *         &lt;element name="Estimation" type="{http://www.pharmml.org/2013/03/StandardisedOutput}EstimationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.pharmml.org/2013/03/CommonTypes}BlockDefnGroup"/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SOBlockType", propOrder = {
    "toolSettings",
    "rawResults",
    "estimation"
})
public class SOBlock
    extends PharmMLRootType
{

    @XmlElement(name = "ToolSettings")
    protected ExternalFile toolSettings;
    @XmlElement(name = "RawResults")
    protected RawResults rawResults;
    @XmlElement(name = "Estimation")
    protected Estimation estimation;
    @XmlAttribute(name = "blkId", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String blkId;

    /**
     * Gets the value of the toolSettings property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalFile }
     *     
     */
    public ExternalFile getToolSettings() {
        return toolSettings;
    }

    /**
     * Sets the value of the toolSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalFile }
     *     
     */
    public void setToolSettings(ExternalFile value) {
        this.toolSettings = value;
    }

    /**
     * Gets the value of the rawResults property.
     * 
     * @return
     *     possible object is
     *     {@link RawResults }
     *     
     */
    public RawResults getRawResults() {
        return rawResults;
    }

    /**
     * Sets the value of the rawResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link RawResults }
     *     
     */
    public void setRawResults(RawResults value) {
        this.rawResults = value;
    }

    /**
     * Gets the value of the estimation property.
     * 
     * @return
     *     possible object is
     *     {@link Estimation }
     *     
     */
    public Estimation getEstimation() {
        return estimation;
    }

    /**
     * Sets the value of the estimation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Estimation }
     *     
     */
    public void setEstimation(Estimation value) {
        this.estimation = value;
    }

    /**
     * Gets the value of the blkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBlkId() {
        return blkId;
    }

    /**
     * Sets the value of the blkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBlkId(String value) {
        this.blkId = value;
    }
    
    /**
     * Creates a new empty {@link ExternalFile} toolSettings element, adds it to the current object and returns it.
     * @return The created {@link ExternalFile} object.
     */
    public ExternalFile createToolSettings(){
    	ExternalFile el = new ExternalFile();
    	this.toolSettings = el;
    	return el;
    }

    /**
     * Creates a new empty {@link RawResults} rawResults element, adds it to the current object and returns it.
     * @return The created {@link RawResults} object.
     */
    public RawResults createRawResults(){
    	RawResults el = new RawResults();
    	this.rawResults = el;
    	return el;
    }

    /**
     * Creates a new empty {@link Estimation} estimation element, adds it to the current object and returns it.
     * @return The created {@link Estimation} object.
     */
    public Estimation createEstimation(){
    	Estimation el = new Estimation();
    	this.estimation = el;
    	return el;
    }


}
