//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.16 at 04:24:00 PM BST 
//


package eu.ddmore.libpharmml.so.dom;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.commontypes.RealValueType;
import eu.ddmore.libpharmml.dom.commontypes.StringValueType;
import eu.ddmore.libpharmml.dom.dataset.ImportDataType;


/**
 * Type defining the target tool messages.
 * 
 * <p>Java class for TargetToolMessagesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetToolMessagesType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.pharmml.org/2013/03/CommonTypes}PharmMLRootType">
 *       &lt;sequence>
 *         &lt;element name="Termination" type="{http://www.pharmml.org/2013/03/CommonTypes}StringValueType" minOccurs="0"/>
 *         &lt;element name="Warnings" type="{http://www.pharmml.org/2013/03/CommonTypes}StringValueType" minOccurs="0"/>
 *         &lt;element name="Errors" type="{http://www.pharmml.org/2013/03/CommonTypes}StringValueType" minOccurs="0"/>
 *         &lt;element name="ElapsedTime" type="{http://www.pharmml.org/2013/03/CommonTypes}RealValueType" minOccurs="0"/>
 *         &lt;element name="OutputFilePath" type="{http://www.pharmml.org/2013/08/Dataset}ImportDataType" minOccurs="0"/>
 *         &lt;element name="ChainsNumber" type="{http://www.pharmml.org/2013/03/CommonTypes}RealValueType" minOccurs="0"/>
 *         &lt;element name="IterationNumber" type="{http://www.pharmml.org/2013/03/CommonTypes}RealValueType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetToolMessagesType", propOrder = {
    "termination",
    "warnings",
    "errors",
    "elapsedTime",
    "outputFilePath",
    "chainsNumber",
    "iterationNumber"
})
public class TargetToolMessages
    extends PharmMLRootType
{

    @XmlElement(name = "Termination")
    protected StringValueType termination;
    @XmlElement(name = "Warnings")
    protected StringValueType warnings;
    @XmlElement(name = "Errors")
    protected StringValueType errors;
    @XmlElement(name = "ElapsedTime")
    protected RealValueType elapsedTime;
    @XmlElement(name = "OutputFilePath")
    protected ImportDataType outputFilePath;
    @XmlElement(name = "ChainsNumber")
    protected RealValueType chainsNumber;
    @XmlElement(name = "IterationNumber")
    protected RealValueType iterationNumber;

    /**
     * Gets the value of the termination property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getTermination() {
        return termination;
    }

    /**
     * Sets the value of the termination property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setTermination(StringValueType value) {
        this.termination = value;
    }

    /**
     * Gets the value of the warnings property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getWarnings() {
        return warnings;
    }

    /**
     * Sets the value of the warnings property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setWarnings(StringValueType value) {
        this.warnings = value;
    }

    /**
     * Gets the value of the errors property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueType }
     *     
     */
    public StringValueType getErrors() {
        return errors;
    }

    /**
     * Sets the value of the errors property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueType }
     *     
     */
    public void setErrors(StringValueType value) {
        this.errors = value;
    }

    /**
     * Gets the value of the elapsedTime property.
     * 
     * @return
     *     possible object is
     *     {@link RealValueType }
     *     
     */
    public RealValueType getElapsedTime() {
        return elapsedTime;
    }

    /**
     * Sets the value of the elapsedTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealValueType }
     *     
     */
    public void setElapsedTime(RealValueType value) {
        this.elapsedTime = value;
    }

    /**
     * Gets the value of the outputFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link ImportDataType }
     *     
     */
    public ImportDataType getOutputFilePath() {
        return outputFilePath;
    }

    /**
     * Sets the value of the outputFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportDataType }
     *     
     */
    public void setOutputFilePath(ImportDataType value) {
        this.outputFilePath = value;
    }

    /**
     * Gets the value of the chainsNumber property.
     * 
     * @return
     *     possible object is
     *     {@link RealValueType }
     *     
     */
    public RealValueType getChainsNumber() {
        return chainsNumber;
    }

    /**
     * Sets the value of the chainsNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealValueType }
     *     
     */
    public void setChainsNumber(RealValueType value) {
        this.chainsNumber = value;
    }

    /**
     * Gets the value of the iterationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link RealValueType }
     *     
     */
    public RealValueType getIterationNumber() {
        return iterationNumber;
    }

    /**
     * Sets the value of the iterationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealValueType }
     *     
     */
    public void setIterationNumber(RealValueType value) {
        this.iterationNumber = value;
    }

}
