//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 11:14:40 AM GMT 
//


package eu.ddmore.libpharmml.so.dom;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import eu.ddmore.libpharmml.dom.commontypes.Rhs;
import eu.ddmore.libpharmml.dom.commontypes.PharmMLRootType;
import eu.ddmore.libpharmml.dom.dataset.ExternalFile;


/**
 * Type specifying task information.
 * 
 * <p>Java class for TaskInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.pharmml.org/pharmml/0.6/CommonTypes}PharmMLRootType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Message" type="{http://www.pharmml.org/so/0.1/StandardisedOutput}MessageType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="OutputFilePath" type="{http://www.pharmml.org/pharmml/0.6/Dataset}ExternalFileType" minOccurs="0"/&gt;
 *         &lt;element name="RunTime" type="{http://www.pharmml.org/pharmml/0.6/CommonTypes}Rhs" minOccurs="0"/&gt;
 *         &lt;element name="NumberChains" type="{http://www.pharmml.org/pharmml/0.6/CommonTypes}Rhs" minOccurs="0"/&gt;
 *         &lt;element name="NumberIterations" type="{http://www.pharmml.org/pharmml/0.6/CommonTypes}Rhs" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskInformationType", propOrder = {
    "messages",
    "outputFilePath",
    "runTime",
    "numberChains",
    "numberIterations"
})
public class TaskInformation
    extends PharmMLRootType
{

    @XmlElement(name = "Message")
    protected List<MessageType> messages;
    @XmlElement(name = "OutputFilePath")
    protected ExternalFile outputFilePath;
    @XmlElement(name = "RunTime")
    protected Rhs runTime;
    @XmlElement(name = "NumberChains")
    protected Rhs numberChains;
    @XmlElement(name = "NumberIterations")
    protected Rhs numberIterations;

    /**
     * Gets the value of the messages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the messages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMessages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MessageType }
     * 
     * 
     */
    public List<MessageType> getMessages() {
        if (messages == null) {
            messages = new ArrayList<MessageType>();
        }
        return this.messages;
    }

    /**
     * Gets the value of the outputFilePath property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalFile }
     *     
     */
    public ExternalFile getOutputFilePath() {
        return outputFilePath;
    }

    /**
     * Sets the value of the outputFilePath property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalFile }
     *     
     */
    public void setOutputFilePath(ExternalFile value) {
        this.outputFilePath = value;
    }

    /**
     * Gets the value of the runTime property.
     * 
     * @return
     *     possible object is
     *     {@link Rhs }
     *     
     */
    public Rhs getRunTime() {
        return runTime;
    }

    /**
     * Sets the value of the runTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rhs }
     *     
     */
    public void setRunTime(Rhs value) {
        this.runTime = value;
    }

    /**
     * Gets the value of the numberChains property.
     * 
     * @return
     *     possible object is
     *     {@link Rhs }
     *     
     */
    public Rhs getNumberChains() {
        return numberChains;
    }

    /**
     * Sets the value of the numberChains property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rhs }
     *     
     */
    public void setNumberChains(Rhs value) {
        this.numberChains = value;
    }

    /**
     * Gets the value of the numberIterations property.
     * 
     * @return
     *     possible object is
     *     {@link Rhs }
     *     
     */
    public Rhs getNumberIterations() {
        return numberIterations;
    }

    /**
     * Sets the value of the numberIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rhs }
     *     
     */
    public void setNumberIterations(Rhs value) {
        this.numberIterations = value;
    }

}
